### ISSUE TITLE
Improve vctrs documentation

### ISSUE THREAD

**Issue by lionel-** [r-lib/vctrs#1016]
* [ ] FAQ about how to implement common types for data frame class and include message in fallback warning implemented in #981.

* [ ] FAQ about lossy cast errors (see also #922).

* [ ] Discussion of promotion vs class hierarchy #980.

**Comment by lionel-** [comment]
The advice for `<foo>` to `<foo>` coercion errors should be different than for `<foo>` to `<bar>` errors.

* The former means the same-class fallback failed because of diverging attribtutes. It always makes sense to implement ptype2 and cast methods for a single class. We should point to a relevant FAQ.

* In the latter case, we should be careful not to encourage implementation of coercion methods too strongly. Instead, the advice should focus on recommending users to normalise their inputs.
