### ISSUE TITLE
vctrs 0.6.0 revdep tracker

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/vctrs#1809]
## rlang related

- [x] photosynthesis: https://github.com/cdmuir/photosynthesis/issues/12
- [x] dplyr: broken from rlang
- [x] rlang: reverse loading version mismatch

## False alarms
- [x] GenomeAdmixR: can't reproduce locally
- [x] portalr: seems related to downloading files
- [x] openalexR: common failure we tend to always see, probably download related
- [x] rapbase: looks related to a download from github failing
